# suppress inspection "UnusedProperty" for whole file
springdoc:
  show-actuator: true

spring:
  cloud:
    openfeign:
      client:
        config:
          product-service:
            url: https://dummyjson.com
  datasource:
    username: sa
    password:
    url: "jdbc:h2:mem:flowable;DB_CLOSE_DELAY=-1"
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
