# suppress inspection "UnusedProperty" for whole file
springdoc:
  show-actuator: true

spring:
  cloud:
    openfeign:
      client:
        config:
          product-service:
            url: https://dummyjson.com
  jpa:
    show-sql: true
