# suppress inspection "UnusedProperty" for whole file
springdoc:
  show-actuator: true

spring:
  cloud:
    openfeign:
      client:
        config:
          another-service:
            url: https://dummyjson.com
