# suppress inspection "UnusedProperty" for whole file
springdoc:
  show-actuator: true

spring:
  cloud:
    openfeign:
      client:
        config:
          product-service:
            url: https://dummyjson.com

#flowable:
#  process-definition-location-prefix: classpath*:/processes/
#  process-definition-location-suffixes: "**.bpmn20.xml,**.bpmn"
