# suppress inspection "UnusedProperty" for whole file
springdoc:
  show-actuator: true

spring:
  cloud:
    openfeign:
      client:
        config:
          product-service:
            url: https://dummyjson.com
#  h2:
#    console.enabled: true
  datasource:
    username: cuba
    password: cuba
    url: "jdbc:postgresql://localhost/spring_boot"
#    driver-class-name: org.h2.Driver
